### ISSUE TITLE
Pacparser stops with "alert" function

### ISSUE THREAD

**Issue by kujiy** [pacparser/pacparser#80]
When I try to debug with chrome://net-internals/#proxy , `alert()` is the best way to know what's happend in the pac. But pacparser doesn't understand `alert()` and show me the following error message and stop working.

```
pac    | JSERROR: PAC script:209:
pac    |     ReferenceError: alert is not defined
pac    | pacparser.c: pacparser_find_proxy: Problem in executing findProxyForURL.
```

I hope pacparser just ignores `alert` and complete the command.
Can anyone tell me how to define empty `alert` function in pacparser?

**Comment by manugarg** [comment]
alert() will most likely not work in an actual PACL script though, right? Because the context in which PAC files are parsed and evaluated by the browser doesn't have 'alert()' defined.

To make it a pass through, you can define the alert function within you PAC file; PAC file is just a javascript for that matter.

**Comment by kujiy** [comment]
Thanks, I understand. It seems that all I have to do is detecting chrome and calling alert().

Here is a sample pac(not tested yet).
```js
	if (typeof alert != "function") {
		function alert(str) {
			var isChrome = /Chrome/.test(navigator.userAgent) && /Google Inc/.test(navigator.vendor); 
			if (isChrome) alert(str);
		}
	}
```

Anyway, I close this issue. 
Thank you.

**Comment by LeeiFrankJaw** [comment]
This library is a joke! A joke! My personal PAC files that works for years over various OSes (Linux, Windows, macOS, iOS) suddenly doesn't work being tested by this library. It throws out various `TypeError`s. What JavaScript/ECMAScript do you have (SpiderMonkey, really)? `Number.parseInt` cannot be used, `String.prototype.endsWith` is not a function. If the library is just to test PACL scripts (personally, I don't know what they are), don't call it PAC tester, call it PACL tester instead.

**Comment by manugarg** [comment]
@LeeiFrankJaw I've no idea why would you comment an issue closed almost 4 years ago. If you want voice your opinion about specific problems, feel free to file a new issue.

Also, I don't understand your outrage. You don't have to use this library. It's for free, otherwise I'd have returned your money for your satisfaction.

**Comment by LeeiFrankJaw** [comment]
Sorry for my outrage yesterday.  I got to know this library from MDN [site](https://developer.mozilla.org/en-US/docs/Web/HTTP/Proxy_servers_and_tunneling/Proxy_Auto-Configuration_(PAC)_file#Predefined_functions_and_environment). I was trying to debug those predefined functions.  Because people from the MDN mentioned this and used this, I though this must be so good and have all the functions mentioned in that article.

I admit my complaints yesterday is a little bit off-topic and impolite. Sorry for that! I was very frustrated yesterday though. I will hide that comment.
